### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghost** [webis-de/unmasking#1]
Hey,

first of all: thank you for sharing your code! 

I directly tried to run it via "./unmask` run examples/gutenberg_test/job.yml", but it results in the following error:

Traceback (most recent call last):
  File "./app/unmask.py", line 101, in <module>
    main()
  File "./app/unmask.py", line 82, in main
    run_in_event_loop(executor.run(config_loader, args.output))
  File "/.../authorship_unmasking/util/util.py", line 112, in run_in_event_loop
    loop.run_until_complete(future)
  File "/.../anaconda3/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/.../authorship_unmasking/util/util.py", line 90, in base_coroutine
    return await cr
  File "/.../authorship_unmasking/job/executors.py", line 89, in run
    await self._run_configuration(executor, config_index, vector, config_variables, job_id, output_dir)
  File "/.../authorship_unmasking/job/executors.py", line 146, in _run_configuration
    await output.save(config_output_dir)
  File "/.../authorship_unmasking/output/formats.py", line 359, in save
    output.add_curve(c, **self._curves[c])
TypeError: add_curve() missing 1 required positional argument: 'values'

Best regards,
Benedikt

**Comment by phoerious** [comment]
Thanks for the report. That's a regression introduced by a recent commit in one of the outputs. I need to figure out why there are no values being passed. You can use an older commit in the meantime (around the time of the NAACL conference should be fine).

**Comment by phoerious** [comment]
The reason why the values field was not filled was a race condition due the way Python handles multi-process communication. I pushed a fix which is not an ideal solution, but it seems to work (for now). I also updated the example job configuration.
