### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Anna-S0phia** [webis-de/unmasking#2]
Hey and hallo,

Thank you for sharing your code! I am so happy that you built it in Python and shared it!

But I got an error while trying the test: ./unmask run examples/gutenberg_test/job.yml 

The repository is quite big, and I would be happy to help me fix it. I just started trying to understand the whole process you have built. I wanted to use it for a current semester project.

The error is containing the following: 

Generating pairs: 6pair(s) [00:04,  1.77pair(s)/s]WARNING: Aborting curve aggregation which blocked for more than 40 seconds. This is probably a bug.
Future exception was never retrieved
future: <Future finished exception=RuntimeError('Cannot publish without initialized MultiProcessingContext')>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/anna/opt/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/anna/Documents/GitHub/unmasking/authorship_unmasking/job/executors.py", line 164, in _exec
    loop.run_until_complete(strat.run(feature_set))
  File "/Users/anna/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/anna/Documents/GitHub/unmasking/authorship_unmasking/unmasking/strategies.py", line 47, in run
    await super().run(fs)
  File "/Users/anna/Documents/GitHub/unmasking/authorship_unmasking/unmasking/interfaces.py", line 196, in run
    await EventBroadcaster().publish("onUnmaskingRoundFinished", event, self.__class__)
  File "/Users/anna/Documents/GitHub/unmasking/authorship_unmasking/event/dispatch.py", line 130, in publish
    raise RuntimeError("Cannot publish without initialized MultiProcessingContext")
RuntimeError: Cannot publish without initialized MultiProcessingContext
"""
The above exception was the direct cause of the following exception:

RuntimeError: Cannot publish without initialized MultiProcessingContext
Future exception was never retrieved
future: <Future finished exception=RuntimeError('Cannot publish without initialized MultiProcessingContext')>
concurrent.futures.process._RemoteTraceback: 
"""

Thanks in advance! 
Beste regards,
Anna Sophia

**Comment by phoerious** [comment]
Closing, since this issue has been fixed a while ago.
